export const actions = {
  GET_DAILY_WEATHER: 'GET_DAILY_WEATHER',
  GET_DAILY_WEATHER_SUCCESS: ' GET_DAILY_WEATHER_SUCCESS',
  GET_DAILY_WEATHER_ERROR: ' GET_DAILY_WEATHER_ERROR',
  SET_ACTIVE_DAY: 'SET_ACTIVE_DAY',
  SET_COORDS_BY_SEARCH: 'SET_COORDS_BY_SEARCH',
}
